Repository jenkinsci/cron_column-plugin, pull requests merged in 2023-01, with the labels that each got.

#4 JENKINS-54846: RAW HTML is shown in cron column since 2.138.2
  src/main/java/hudson/plugins/CronViewColumn.java
  src/main/resources/hudson/plugins/CronViewColumn/column.jelly
Labels: bug

#8 Update screenshot
  README.md
  docs/images/cron-column.jpg
  docs/images/cron-column.png
Labels: documentation

#10 Support Pipeline jobs
  src/main/java/hudson/plugins/CronViewColumn.java
Labels: enhancement
